version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: daily
      open-pull-requests-limit: 10
      target-branch: next
      versioning-strategy: increase
      commit-message:
          prefix: chore
          include: scope
